AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String

  DomainTLSCertificateArn:
    Type: String

  PublicS3BucketName:
    Type: String
  
  PublicS3Prefix:
    Type: String

Resources:
  CfDistribution:
    Type: "AWS::CloudFront::Distribution"
    Metadata:
      Comment: 'Distribution for portfolio app'
    Properties:
      DistributionConfig:
        Comment: 'A simple distribution with an S3 origin'
        Aliases:
          - !Sub ${DomainName}
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Sub 's3-origin-${PublicS3BucketName}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: !Sub 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainTLSCertificateArn
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub '${PublicS3BucketName}.s3.amazonaws.com'
            Id: !Sub 's3-origin-${PublicS3BucketName}'
            OriginPath: !Sub "/${PublicS3Prefix}"
        PriceClass: 'PriceClass_All'




    
